# Generated by Django 5.0.6 on 2025-02-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://nanilovestocook.com/wp-content/uploads/2022/08/placeholder.png', max_length=500),
        ),
    ]
